spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://xxx/mybatisplus_demo?useUnicode=true&characterEncoding=utf-8
      username: xxx
      password: xxx
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 连接池名称
      pool-name: MyHikariCPOfMaster
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      connection-test-query: SELECT 1
    db2:
      jdbc-url: jdbc:mysql://xxx/mybatisplus_demo?useUnicode=true&characterEncoding=utf-8
      username: xxx
      password: xxx
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 连接池名称
      pool-name: MyHikariCPOfMaster
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      connection-test-query: SELECT 1
  application:
    name: multipledatasources-demo-server

server:
  port: 8092
