spring:
  redis:
    database: 0 # redis 数据库索引（默认为0）
    host: 47.101.135.160
    password: root # redis 服务器连接密码（默认为空）
    port: 6379
    timeout: 12000  # 连接超时时间（毫秒），默认2000ms
    # cluster:
    # nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
    # maxRedirects: 6
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

server:
  port: 8095